# Generated by Django 5.2.8 on 2025-11-30 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('happy_pct', models.FloatField(default=0)),
                ('sad_pct', models.FloatField(default=0)),
                ('angry_pct', models.FloatField(default=0)),
                ('fear_pct', models.FloatField(default=0)),
                ('surprise_pct', models.FloatField(default=0)),
                ('disgust_pct', models.FloatField(default=0)),
                ('neutral_pct', models.FloatField(default=0)),
                ('head_down_count', models.IntegerField(default=0)),
                ('hunched_count', models.IntegerField(default=0)),
                ('hands_on_face_count', models.IntegerField(default=0)),
                ('overall_state', models.CharField(choices=[('stable', 'Estable'), ('anxious', 'Ansiedad detectada'), ('sad', 'Tristeza detectada'), ('stressed', 'Estrés detectado'), ('nervous', 'Nerviosismo detectado')], default='stable', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('genere', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_type', models.CharField(choices=[('high_sadness', 'Tristeza elevada'), ('high_anxiety', 'Ansiedad elevada'), ('high_anger', 'Irritabilidad elevada'), ('nervous_behavior', 'Comportamiento nervioso'), ('depressive_posture', 'Postura depresiva')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='low', max_length=10)),
                ('message', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='db.analysissession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dominant_emotion', models.CharField(choices=[('happy', 'Feliz'), ('sad', 'Triste'), ('angry', 'Enojado'), ('fear', 'Miedo'), ('surprise', 'Sorpresa'), ('disgust', 'Disgusto'), ('neutral', 'Neutral')], max_length=15)),
                ('happy_score', models.FloatField(default=0)),
                ('sad_score', models.FloatField(default=0)),
                ('angry_score', models.FloatField(default=0)),
                ('fear_score', models.FloatField(default=0)),
                ('surprise_score', models.FloatField(default=0)),
                ('disgust_score', models.FloatField(default=0)),
                ('neutral_score', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='db.analysissession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='analysissession',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='db.person'),
        ),
        migrations.CreateModel(
            name='PostureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('head_down', models.BooleanField(default=False)),
                ('hunched_shoulders', models.BooleanField(default=False)),
                ('hands_on_face', models.BooleanField(default=False)),
                ('nose_x', models.FloatField(blank=True, null=True)),
                ('nose_y', models.FloatField(blank=True, null=True)),
                ('left_shoulder_x', models.FloatField(blank=True, null=True)),
                ('left_shoulder_y', models.FloatField(blank=True, null=True)),
                ('right_shoulder_x', models.FloatField(blank=True, null=True)),
                ('right_shoulder_y', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postures', to='db.analysissession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
